#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Nov 26 03:39:45 PST 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 4dd3049512a74449ad6cae1a5b8c1d93 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot test_adc_driver_behav xil_defaultlib.test_adc_driver xil_defaultlib.glbl -log elaborate.log"
xelab -wto 4dd3049512a74449ad6cae1a5b8c1d93 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot test_adc_driver_behav xil_defaultlib.test_adc_driver xil_defaultlib.glbl -log elaborate.log

